# Generated by Django 3.0.5 on 2020-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burger',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='burger',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='burger',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='burger',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='burger',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='burger',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='burgers', to='api.Ingredient'),
        ),
    ]
